### ISSUE TITLE
How to fix apache run alway after exit vagrant ssh.

### ISSUE THREAD

**Issue by Pakinwet** [ArminVieweg/ubuntu-bionic-lamp#2]

**Comment by a-r-m-i-n** [comment]
Sorry?

**Comment by Pakinwet** [comment]
I founded a problem when I quit "vagrant ssh". This causes Apache to stop working.

Every time I use the "vagrant up" command, I have to start in apache every time. Do you have any recommendations for me to use?

**Comment by Pakinwet** [comment]
I've solved this issue by added `Mutex flock` to the Mutex section into `/etc/apache2/apache2.conf ` file.
Cr. https://stackoverflow.com/questions/50652808/apache-shutdown-couldnt-grab-mutex
